# Generated by Django 4.2.2 on 2024-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0017_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
