# Generated by Django 5.0.3 on 2024-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0018_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=True),
        ),
    ]
