# Generated by Django 5.0.3 on 2024-05-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0020_alter_answer_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeanswer',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='likequestion',
            name='is_liked',
        ),
    ]
