# Generated by Django 5.0.3 on 2024-03-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0005_profile_like_count_question_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='question', to='asker.tag'),
        ),
    ]
