# Generated by Django 5.0.3 on 2024-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0010_answer_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
