# Generated by Django 4.2.2 on 2024-05-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0015_alter_likeanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
