# Generated by Django 4.2.2 on 2024-05-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0016_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
